# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DXG19unCAjYmNDoFO9oDnh_E73KdeLKg
"""



"""Data Collection and Preparation"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data into a Pandas DataFrame
df = pd.read_csv('/content/sales_data-set[1].csv')  # Replace 'your_file.csv' with the actual file name

# Display the first few rows of the dataset
df.head()

# Check for missing values and data types
df.info()
df.isnull().sum()





# Drop missing values
df.dropna(inplace=True)

# Convert date columns to datetime format
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y') # Added format string to specify the date format

# Aggregate sales by month
df['Month'] = df['Date'].dt.to_period('M')
monthly_sales = df.groupby('Month')['Sales'].sum() # Changed this line to sum only the 'Sales' column

# Plot the sales trend
plt.figure(figsize=(12, 6))
monthly_sales.plot()
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.grid(True)
plt.show()

# Identify peak sales periods
peak_sales = monthly_sales.sort_values(ascending=False).head(10)
print("Top 10 Peak Sales Months:")
print(peak_sales)

# Determine the most popular products
top_products = df.groupby('Product')['Sales'].sum().sort_values(ascending=False).head(10)

# Bar chart for top-selling products
plt.figure(figsize=(10, 6))
top_products.plot(kind='bar')
plt.title('Top-Selling Products')
plt.xlabel('Product')
plt.ylabel('Total Sales')
plt.grid(True)
plt.show()

data_selling_product = {'Product A': 100, 'Product B': 150, 'Product C': 200}